(function(root){
 'use strict';
 const button=(action,id,text)=>`<button class="button secondary" data-action="${action}" data-id="${id}">${text}</button>`;
 const date=value=>value?new Intl.DateTimeFormat('ja-JP',{timeZone:'Asia/Tokyo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(value))+' JST':'保存日時は未記録';
 function versions(pr,q,s,h){const P=root.Preparation,current=P.current(s,pr.id,q.id);if(!current)return '<p class="boundary">版はまだ保存されていません。</p>';const others=P.es(s,pr.id,q.id).versions.filter(v=>v.number!==current.number).slice().reverse();
  const card=v=>`<article class="source-card"><h3>${v.confirmed?'本人確認版':'未確認の草稿'} · Version ${v.number}</h3><small>${h.esc(date(v.savedAt))}</small><p class="preserve">${h.esc(v.text)}</p>${!v.confirmed?button('confirm-version',pr.id+'/'+q.id+'/'+v.number,'この版を本人確認版にする'):''}</article>`;
  return card(current)+`<details><summary>他の版 (${others.length}) · 新しい未確認草稿もここに保存</summary>${others.map(card).join('')||'<p>他の版はありません。</p>'}</details><p class="boundary">本人確認は内容の確認です。実際の提出完了は受領通知など別の証拠で扱います。</p>`;
 }
 function materials(pr,p,s,h,ui){const R=root.Records,C=root.Catalog,types=['all','企業研究','ES','面接準備','応募記録','その他'],filter=types.includes(ui.materialType)?ui.materialType:'all',readiness=R.readiness(p,s,pr.id),docs=R.materials(s,pr.id).filter(d=>d.format!=='json'&&(filter==='all'||d.type===filter));
  const card=d=>{const q=C.esQuestions.find(q=>d.id===pr.id+'/'+q.id);return `<article class="source-card"><div class="message-tags">${h.tag(d.type)}</div><h3>${h.esc(d.title)}</h3>${q?versions(pr,q,s,h):`<small>${h.esc(d.date||'日付未記録')}${d.format==='pdf'?' / サンプル草稿 · Version 1':''}</small><p class="preserve">${h.esc(d.body)}</p>${d.format==='pdf'?button('download-cv',pr.id,'架空の履歴書PDFをダウンロード'):''}`}</article>`;};
  const main=docs.filter(d=>d.type!=='面接準備'||readiness.ready),standby=docs.filter(d=>d.type==='面接準備'&&!readiness.ready);
  return `<div class="notice">資料はすべて新しく作った架空例です。説明会・経験談は企業研究、自分の応募書類はESとして探せます。</div><div class="work-toolbar"><label class="field">用途<select id="material-type">${types.map(t=>`<option value="${t}" ${t===filter?'selected':''}>${t==='all'?'すべて':t}</option>`).join('')}</select></label>${button('sample-versions',pr.id,'3版の架空ESを追加して試す')}</div>${main.map(card).join('')||'<p>この用途の資料はありません。</p>'}${standby.length?`<details class="standby"><summary>予備の面接資料 (${standby.length}) · 現在は待機</summary><p>${h.esc(readiness.reason)}</p>${standby.map(card).join('')}</details>`:''}`;
 }
 function review(p,s,h,ui){const R=root.Records,rows=R.pending(p.actions,s,h.isDone),future=rows.filter(a=>a.scheduledAt),current=rows.filter(a=>!a.scheduledAt);
  const legacy=a=>`<article class="source-card"><h3>${h.esc(a.title)}</h3><p>${h.esc(h.company(a.companyId).name)} / ${a.deadline?'以前の期限 '+h.esc(h.fmt(a.deadline))+' JST':'期限未確認'} / 架空の遺留項目</p>${button('review-done',a.id,'本人回答：完了')}${button('review-cancel',a.id,'本人回答：もう行わない')}</article>`;
  const row=a=>a.origin==='notice'?h.taskRow(a):legacy(a);
  return `<div class="page-title"><div><div class="eyebrow">DAILY RECONCILIATION</div><h1>未完了を、全部確かめる。</h1><p>確認基準日：架空の2030年5月14日。過去・無期限・未来の予定を省略せず、根拠と本人回答で更新します。</p></div></div><div class="notice">この画面は手動で試せる日次確認です。実際の夜間実行・メール確認・通知送信は接続していません。返答なしでは何も完了にしません。</div><section class="panel work-panel"><h2>受領通知は対応する一歩だけ</h2><p>AIインターンは回答フォームと適性テストが別項目です。受領通知を反映しても、テストや書類結果は更新しません。</p>${button('receipt','es-received',s.records.receipts.length?'同じ受領通知を再度反映':'架空の回答フォーム受領通知を反映')}${button('record-source','es-received','通知全文を見る')}<p>未完了 ${rows.length} 件。完了・取消済み・定期確認の例は対象外です。</p></section><section class="panel work-panel"><h2>対応事項（過去・期限未確認も含む）</h2>${current.map(row).join('')||'<p>残っている対応事項はありません。</p>'}</section><section class="panel work-panel"><h2>予約済み・未来の準備</h2>${future.map(row).join('')||'<p>確認できた未来の準備はありません。</p>'}</section><section class="panel work-panel"><h2>本人の返信から活動日誌へ</h2><label class="field">架空の本人返答<textarea rows="4" data-journal="yes" placeholder="例：【架空】資料を見直して逆質問を整理した。">${h.esc(ui.journalDraft??s.records.journal)}</textarea></label>${button('save-journal','','この返答を日誌に保存')}<p class="boundary">通知の受付やタスクの完了から日誌を推測しません。空欄なら保存しません。入力はこのブラウザ内だけに保存します。</p>${s.records.journal?`<h3>保存した返答</h3><p class="preserve">${h.esc(s.records.journal)}</p>`:''}</section>`;
 }
 function guide(){return `<div class="page-title"><div><div class="eyebrow">6 MINUTE WALKTHROUGH</div><h1>通知から、必要な一歩まで。</h1><p>全データは独自に作った架空例。順にクリックすると、状態がどう変わるか確認できます。</p></div></div><section class="panel work-panel"><ol class="walkthrough"><li><h3>通知と根拠</h3>${button('process','','12件の通知を仕分ける')}<p>4社・7プロジェクト。招待と予約、提出と取消期限を区別します。</p></li><li><h3>資料と確認版</h3>${button('sample-versions','aster-pm','Aster本選考に架空ESを3版追加')}<p><a href="#project/aster-pm/materials">資料・版を開く →</a> 本人確認v2が先に表示され、後日のv3草稿は「他の版」に残ります。PDFもダウンロードできます。</p></li><li><h3>研究からESへ</h3><p><a href="#project/aster-pm/research">研究・素材棚 →</a> 収集と蒸留を試し、<a href="#project/aster-pm/es">ES編集 →</a>で修正・版保存・本人確認します。収集内容と助言は架空の固定例／簡易ルールです。</p></li><li><h3>今必要な準備</h3><p><a href="#project/aster-ai/interview">AIインターンの待機画面 →</a> 受領だけで書類通過にしません。架空のAI面接案内を反映すると「書類選考中」のまま練習が開きます。本選考の明示的な面談案内も別に確認できます。</p></li><li><h3>受領と未完了の照合</h3><p><a href="#review">未完了の確認 →</a> 回答フォーム受領を反映し、適性テストが残ること、古い・無期限の項目も残ることを確認。本人返答でだけ日誌を保存します。</p></li><li><h3>予定と再実行</h3><p><a href="#calendar">Calendar →</a> 模擬同期と改期を試します。Google/Outlookには接続しません。ICSは架空予定を含む実ファイルです。通知を再実行して、重複しないことを確かめます。</p></li></ol></section><section class="panel work-panel"><h2>このブラウザで実行されるもの</h2><p>編集、版保存・確認、履歴表示、用途別表示、状態ルール、回答保存、未完了更新、PDF・ICS生成とダウンロード、ローカル保存。</p><h2>架空例・接続していないもの</h2><p>通知本文、抽出結果、企業研究、経験談、面接の固定質問は架空例。メール・採用サイト・AI API・外部カレンダーへの認証、応募や送信、夜間の自動処理は行いません。入力を外部へ送信しません。</p></section>`;}
 root.RecordViews={versions,materials,review,guide};
})(typeof window!=='undefined'?window:globalThis);
