(function(root){
 'use strict';
 function render(route,p,s,h,ui){
  const C=root.Catalog,P=root.Preparation,R=root.Records,V=root.RecordViews,{esc,tag,fmt,company,messageRow,taskRow}=h;
  const [view,id,tab='overview']=route.split('/');
  const link=(url,text,primary=false)=>`<a class="button ${primary?'primary':'secondary'}" href="#${esc(url)}">${esc(text)} →</a>`;
  const button=(action,id,text,disabled=false)=>`<button class="button secondary" data-action="${action}" data-id="${esc(id)}" ${disabled?'disabled':''}>${esc(text)}</button>`;
  const title=(k,t,sub)=>`<div class="page-title"><div><div class="eyebrow">${k}</div><h1>${esc(t)}</h1><p>${esc(sub)}</p></div></div>`;
  const empty=text=>`<div class="empty"><p>${esc(text)}</p></div>`;
  const panel=(heading,body)=>`<section class="panel work-panel"><h2>${esc(heading)}</h2>${body}</section>`;
  const stateLabel=x=>({active:'選考・予定あり',preparing:'検討・準備中',watching:'保存中',closed:'今回は見送り',incoming:'判断待ち'}[x]||'判断待ち');
  function projectCard(pr){const item=p.projects.find(x=>x.id===pr.id)||{};const tasks=h.visibleActions(p).filter(a=>a.projectId===pr.id&&!h.isDone(a));const next=tasks.find(a=>a.deadline);return `<article class="panel work-panel"><div class="eyebrow">${esc(company(pr.companyId).name)} / ${esc(pr.type)}</div><h2>${esc(pr.name)}</h2><p>${esc(pr.role)}</p><div class="message-tags">${tag(stateLabel(item.stage),'green')}${tag(tasks.length+' アクション')}</div><p>${next?'次の回答・提出期限 '+fmt(next.deadline)+' JST':'確認できた提出期限はありません'}</p>${link('project/'+pr.id,'プロジェクトを開く',true)}</article>`;}
  function cards(list){return `<div class="work-grid">${list.map(projectCard).join('')}</div>`;}
  function sourceCard(x){return `<article class="source-card"><div class="message-tags">${tag(x.provider+'（模擬）',x.kind==='official'?'green':'purple')}${tag(x.year+' / '+x.round)}</div><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p><small>架空資料 ID: ${esc(x.id)}</small></article>`;}
  function research(companyId,projectId){const profile=C.profiles[companyId],collected=C.sources.filter(x=>x.companyId===companyId&&s.collected.includes(x.id)&&(!projectId||!x.projectId||x.projectId===projectId));
   const last=s.collections.filter(r=>r.companyId===companyId).at(-1);
   return `<div class="notice">全資料は独自に作った架空例です。OpenWork・BizCampus・外資就活・ONE CAREER の実投稿や実際の取得結果ではありません。体験談は年度・コースごとに照合します。</div><div class="work-toolbar">${button('collect',companyId,'サンプル収集を実行')}${projectId?button('distill',projectId,'経験談を蒸留して素材棚へ'):''}<span>${last?`前回実行 ${fmt(last.at)} JST / 追加 ${last.added}・既存 ${last.skipped}`:'未収集 / 外部通信なし'}</span></div>
   ${panel('7 つの観点で企業を理解する',`<div class="dimension-grid">${C.dimensions.map((d,i)=>`<article><span class="eyebrow">0${i+1} / ${i>=4?'DIFFERENTIATION':'FOUNDATION'}</span><h3>${esc(d)}</h3><p>${esc(profile.cells[i])}</p><small>架空根拠：${esc(companyId)}-${i===4?'comparison（下記の業界比較）':'official-'+(i===6?2:i===2||i===5?0:1)}</small></article>`).join('')}</div>`)}
   ${panel('志望動機の切り口と逆質問',`<div class="message-tags">${profile.keywords.map(v=>tag(v,'blue')).join('')}</div><p>${esc(profile.question)}</p><p class="boundary">比較から作った仮説です。自分の経験との接点と、現場で確かめたい点を付け足して使います。</p>`)}
   ${panel('出典ライブラリ',collected.length?collected.map(sourceCard).join(''):empty('「サンプル収集を実行」で模擬出典を取り込みます。'))}
   ${projectId?panel('このプロジェクトの蒸留素材棚',(s.notes[projectId]||[]).length?(s.notes[projectId]||[]).map(id=>{const x=C.sources.find(v=>v.id===id);return `<article class="source-card"><h3>${esc(x.lesson)}</h3><p>${esc(x.provider)}（模擬） / ${x.year} / ${esc(x.round)}</p><p>練習への転用：自分の実際の経験で説明できるか確認し、答えられない点を面接準備へ。</p><details><summary>出典と文脈を見る</summary><p>${esc(x.body)}</p><small>${esc(x.id)}</small></details></article>`;}).join(''):empty('収集後に蒸留ボタンを押すと、このコースの経験談だけを保存します。')):''}`;
  }
  function industry(){return panel('業界比較｜架空の 4 社を同じ軸で見る',`<div class="table-scroll"><table class="scope-table"><thead><tr><th>会社</th><th>価値・収益</th><th>強みと代償</th><th>深掘りする問い</th></tr></thead><tbody>${Object.entries(C.profiles).map(([id,x])=>`<tr><td><a href="#company/${id}">${esc(company(id).name)}</a></td><td>${esc(x.cells[3])}</td><td>${esc(x.cells[4])}</td><td>${esc(x.question)}</td></tr>`).join('')}</tbody></table></div><p class="boundary">比較は架空プロフィールからの推論。実在企業の優劣を示す表ではありません。</p>`);}
  function esPage(pr){return `<div class="notice">公開デモ用の架空文です。入力はこのブラウザ内に保存。具体性・深掘り・表現の順で見直し、自分で修正してから文字数を再確認します。</div>${C.esQuestions.map(q=>{const d=P.es(s,pr.id,q.id);return panel(q.label,`<label class="field">編集する草稿（確認版とは別）<textarea rows="7" data-draft="${pr.id}" data-question="${q.id}">${esc(d.text)}</textarea></label><div class="work-toolbar"><span id="count-${q.id}" role="status">${P.count(d.text)} / ${q.limit} 字</span>${button('version',pr.id+'/'+q.id,'この稿を版として保存')}${button('review-es',pr.id,'3 観点で再チェック')}</div><p class="boundary">改行・記号を含めて数えます。提出先のカウンターも確認してください。</p><div class="review-grid">${P.review(d.text,q.limit).map(r=>`<article><h3>${r.label}</h3><p>${esc(r.text)}</p></article>`).join('')}</div>${V.versions(pr,q,s,h)}`);}).join('')}`;}
  function interview(pr){const readiness=R.readiness(p,s,pr.id);if(!readiness.ready)return `<div class="notice"><h2>面談・面接準備は待機</h2><p>${esc(readiness.reason)}</p></div>${pr.id==='aster-ai'?button('invite-ai',pr.id,'架空の書類選考AI面接案内を反映')+button('stage-source','ai-invitation','案内全文を見る'):pr.id==='kumo-product'?button('screening-pass',pr.id,'架空の書類通過通知を反映')+button('stage-source','screening-pass','結果全文を見る'):''}<details><summary>予備の深掘りメモを見る</summary><p>今は提出事項と企業研究を確認。先に保存した回答は予備として残ります。</p></details>${link('project/'+pr.id+'/materials','資料を確認')}`;const round=pr.rounds.includes(ui.round)?ui.round:pr.rounds[0],q=Math.max(0,Math.min(2,ui.question||0)),a=P.answers(s,pr.id,round),questions=C.questions(pr,round),versions=C.esQuestions.flatMap(x=>[P.current(s,pr.id,x.id)].filter(Boolean).map(v=>({...v,label:x.label}))),notes=s.notes[pr.id]||[];
   return `<div class="notice"><p>${esc(readiness.reason)}</p>${pr.id==='aster-ai'&&s.records.aiInvited?button('stage-source','ai-invitation','案内全文を見る'):pr.id==='kumo-product'&&s.records.docPassed?button('stage-source','screening-pass','結果全文を見る'):''}想定問答は架空のコースに合わせた固定質問です。入力と簡易振り返りが動作します。AI 面接官・音声評価・合否予測は接続していません。</div>
   ${panel('面接準備パック',`<p>${esc(pr.focus)}</p><div class="message-tags">${C.profiles[pr.companyId].keywords.map(x=>tag(x,'blue')).join('')}</div><details><summary>参照する ES（本人確認版を優先） (${versions.length})</summary>${versions.map(v=>`<h3>${esc(v.label)} · v${v.number} · ${v.confirmed?'本人確認版':'未確認の草稿'}</h3><p class="preserve">${esc(v.text)}</p>`).join('')||'<p>ES タブで版を保存してください。</p>'}</details><details><summary>このコースの経験談から (${notes.length})</summary>${notes.map(id=>{const x=C.sources.find(x=>x.id===id);return `<p>${esc(x.lesson)} <small>— ${esc(x.provider)}（模擬） / ${x.year} / ${esc(x.round)} / ${esc(x.id)}</small></p>`;}).join('')||'<p>研究タブで収集・蒸留してください。</p>'}</details><h3>逆質問候補</h3><p>${esc(C.profiles[pr.companyId].question)}</p>`)}
   ${panel('一問ずつ練習する',`<label class="field">面接の段階<select id="interview-round">${pr.rounds.map(r=>`<option ${r===round?'selected':''}>${esc(r)}</option>`).join('')}</select></label><div class="question-box"><span class="eyebrow">${esc(round)} / QUESTION ${q+1} OF 3</span><h2>${esc(questions[q])}</h2><label class="field">あなたの回答<textarea rows="7" data-answer="${pr.id}" data-round="${esc(round)}" data-q="${q}">${esc(a[q]||'')}</textarea></label><details><summary>深掘りを受ける</summary><p>${q===0?'同業他社の別コースでも実現できませんか？ 配属が希望と違った場合は？':q===1?'別案を退けた根拠は？ チームの成果のうち、あなた自身の貢献は？':'その指標が改善しても利用者が困る場合は？ 最初の仮説が外れたら？'}</p></details></div><div class="work-toolbar">${button('prev-question',pr.id,'前の質問')}${button('next-question',pr.id,'次の質問')}${button('feedback',pr.id,'弱点を振り返る')}</div>${ui.feedback?`<div class="review-grid">${P.feedback(s,pr.id,round).map(f=>`<article><h3>質問 ${f.q+1}</h3><p>${esc(f.text)}</p></article>`).join('')}</div>`:''}`)}`;
  }
  if(view==='guide')return V.guide();
  if(view==='review')return V.review(p,s,h,ui);
  if(view==='companies')return title('COMPANY → PROJECT → PREPARATION','会社から、準備の全体像へ。','会社を開くと、同じ会社の本選考・インターン・イベントを別々に確認できます。')+`<div class="work-grid">${root.DemoData.companies.map(c=>panel(c.name,`<p>${esc(c.description)}</p><p>${C.projects.filter(x=>x.companyId===c.id).length} プロジェクト / ${p.messages.filter(x=>x.companyId===c.id).length} 通知</p>${link('company/'+c.id,'会社を開く',true)}`)).join('')}</div>`;
  if(view==='pipeline')return title('PROJECT PIPELINE','プロジェクトごとの進捗。','応募コースごとに意向・選考の事実・締切を管理します。')+cards(C.projects);
  if(view==='research')return title('RESEARCH → DISTILL → APPLY','比較して、自分の言葉へ。','企業の7観点、業界比較、コース別経験談を準備につなぎます。')+industry()+cards(C.projects);
  if(view==='interview')return title('PREPARATION ROOM','企業とコースに合わせて練習。','プロジェクトを選び、面接準備タブを開いてください。')+`<div class="work-grid">${C.projects.map(pr=>panel(pr.name,`<p>${esc(company(pr.companyId).name)} / ${esc(pr.rounds.join(' → '))}</p><p>${esc(R.readiness(p,s,pr.id).reason)}</p>${link('project/'+pr.id+'/interview',R.readiness(p,s,pr.id).ready?'面談・面接準備へ':'現在の段階を確認',true)}`)).join('')}</div>`;
  if(view==='company'){const c=root.DemoData.companies.find(x=>x.id===id);if(!c)return empty('会社が見つかりません。');return title('COMPANY WORKSPACE',c.name,c.description)+cards(C.projects.filter(x=>x.companyId===id))+panel('会社別メール',p.messages.filter(m=>m.companyId===id).map(m=>messageRow(m,true)).join('')||empty('概要からサンプルを仕分けると表示されます。'))+research(id)+industry();}
  if(view==='project'){const pr=C.projects.find(x=>x.id===id);if(!pr)return empty('プロジェクトが見つかりません。');const current=p.projects.find(x=>x.id===id)||{},tasks=p.actions.filter(a=>a.projectId===id),events=p.calendar.filter(a=>a.projectId===id);
   const tabs=[['overview','締切・進捗'],['materials','資料・版'],['mail','メール'],['es','ES'],['research','研究・素材棚'],['interview','面接準備']];
   const header=`<a class="button text" href="#company/${pr.companyId}">← ${esc(company(pr.companyId).name)} の全プロジェクト</a>`+title('PROJECT WORKSPACE',pr.name,pr.role)+`<nav class="work-tabs" aria-label="プロジェクト内">${tabs.map(([t,label])=>`<a href="#project/${id}/${t}" ${t===tab?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;
   if(tab==='materials')return header+V.materials(pr,p,s,h,ui);if(tab==='es')return header+esPage(pr);if(tab==='research')return header+research(pr.companyId,id);if(tab==='interview')return header+interview(pr);
   if(tab==='mail')return header+panel('このプロジェクトの通知',p.messages.filter(m=>m.projectId===id).map(m=>messageRow(m,true)).join('')||empty('このプロジェクトに確認できた通知はありません。'));
   return header+`<div class="two-column">${panel('締切と次の行動',tasks.map(taskRow).join('')||empty('確認できた締切・個別タスクはありません。'))}${panel('判断と準備',`<div class="message-tags">${tag(stateLabel(current.stage),'green')}${tag(pr.type)}</div><label class="field">このコースへの意向<select data-decision="${id}">${[['undecided','判断待ち'],['pursue','検討を進める'],['save','保存する'],['decline','今回は見送る']].map(([v,t])=>`<option value="${v}" ${current.decision===v?'selected':''}>${t}</option>`).join('')}</select></label><p>意向を変えても、確認済みの予約・本人向け提出課題は取り消されません。</p>${link('project/'+id+'/es','ES を準備')}${link('project/'+id+'/research','研究を開く')}`)}</div>`+panel('確定した予定と取消期限',events.map(e=>`<article class="source-card"><h3>${esc(e.title)}</h3><p>開催 ${fmt(e.start)}–${fmt(e.end)} JST</p><p>キャンセル期限：${e.cancellationDeadline?fmt(e.cancellationDeadline)+' JST':'記載なし'}</p>${button('source',e.sourceId,'確認メールを見る')}</article>`).join('')||empty('予約確認はまだありません。'));
  }
  if(view==='calendar'){const cal=s.calendar,last=cal.runs.at(-1);return title('CALENDAR CONNECTION DEMO','確定した予定を、カレンダーへ。','ワンクリックで模擬接続。招待を予約済みにせず、確定した日程だけを同期します。')+`<div class="notice">接続はシミュレーションです。Google / Outlook への認証や書き込みは行いません。ICS は架空の予定を手動で取り込める実ファイルです。繰り返し取り込む際の重複処理はカレンダー側に依存します。</div>`+panel('接続と同期',`<div class="work-toolbar">${tag(cal.connected?'デモ接続中':'未接続',cal.connected?'green':'gray')}${button(cal.connected?'disconnect-calendar':'connect-calendar','',cal.connected?'デモ接続を解除':'Calendar に接続（デモ）')}${cal.connected?button('sync-calendar','','今の予定を同期'):''}${p.calendar.length?button('download-ics','','架空の予定を ICS でダウンロード'):''}</div><p>${last?`直近の同期：追加 ${last.added} / 更新 ${last.updated} / 既存 ${last.skipped} / 削除 ${last.removed}`:'まだ同期していません。概要で通知を仕分けてください。'}</p><p>確定予定 ${p.calendar.length} 件 / 日程重複 ${p.conflicts.length} 件</p>${button('update','',!p.messages.length?'先に概要で通知を仕分けてください':p.messages.some(m=>m.id===root.DemoData.update.id)?'日程変更は反映済':'Aster の日程変更サンプルを反映',!p.messages.length||p.messages.some(m=>m.id===root.DemoData.update.id))}<p class="boundary">デモ接続中は、通知の日程変更も同じ予定 ID に反映します。</p>`)+panel('取り込み対象の確定予定',p.calendar.map(e=>`<article class="source-card"><div class="eyebrow">${esc(company(e.companyId).name)} / ${esc(C.projects.find(p=>p.id===e.projectId)?.name||'プロジェクト未確認')}</div><h3>${esc(e.title)}</h3><p>${fmt(e.start)}–${fmt(e.end)} JST</p>${button('source',e.sourceId,'根拠を見る')}<small>UID: ${esc(e.id)}@example.com</small></article>`).join('')||empty('概要でサンプルを仕分けると、確定した予定が表示されます。'));}
  return empty('ページが見つかりません。');
 }
 root.Workbench={render};
})(typeof window!=='undefined'?window:globalThis);
